//! Writers for the other log formats, so the demo can be converted to try the parsers on
//! files laid out as real tools write them, and for round-trip tests.

use std::fs::File;
use std::io::{self, BufWriter, Seek, SeekFrom, Write};

use can_core::{flags, FrameRef, FrameStore, EXT_FLAG};

/// Writes `store` to `path` in the format its extension names.
pub fn convert(store: &FrameStore, path: &str) -> Result<(), String> {
    let extension = path.rsplit_once('.').map(|(_, e)| e.to_ascii_lowercase());
    let file = File::create(path).map_err(|e| format!("{path}: {e}"))?;
    let mut out = BufWriter::with_capacity(1 << 20, file);
    let result = match extension.as_deref() {
        Some("asc") => write_asc(store, &mut out),
        Some("trc") => write_trc(store, &mut out),
        Some("csv") => write_csv(store, &mut out),
        Some("blf") => write_blf(store, &mut out),
        Some("mf4") => write_mf4(store, &mut out),
        _ => {
            return Err(format!(
                "{path}: the extension must be .asc, .trc, .csv, .blf or .mf4"
            ))
        }
    };
    result
        .and_then(|()| out.flush())
        .map_err(|e| format!("{path}: {e}"))
}

/// Vector ASC, base hex with absolute timestamps from the second of the first frame.
pub fn write_asc(store: &FrameStore, out: &mut impl Write) -> io::Result<()> {
    let start_s = store.first_ts_ns().unwrap_or(0).div_euclid(1_000_000_000);
    let date = asc_date(start_s);
    writeln!(out, "date {date}")?;
    writeln!(out, "base hex  timestamps absolute")?;
    writeln!(out, "internal events logged")?;
    writeln!(out, "Begin Triggerblock {date}")?;
    writeln!(out, "   0.000000 Start of measurement")?;
    for index in 0..store.len() {
        let frame = store.frame(index);
        let offset_ns = frame.ts_ns - start_s * 1_000_000_000;
        let channel = u32::from(frame.channel) + 1;
        write!(
            out,
            "{:4}.{:06} ",
            offset_ns / 1_000_000_000,
            offset_ns % 1_000_000_000 / 1000
        )?;
        let direction = if frame.flags & flags::TX != 0 {
            "Tx"
        } else {
            "Rx"
        };
        if frame.flags & flags::ERROR != 0 {
            writeln!(out, "{channel}  ErrorFrame")?;
        } else if frame.flags & flags::FD != 0 {
            let brs = u32::from(frame.flags & flags::BRS != 0);
            let esi = u32::from(frame.flags & flags::ESI != 0);
            let fd_flags = 0x1000 | brs << 13 | esi << 14;
            write!(
                out,
                "CANFD {channel:3} {direction:<4} {:>8}  {brs} {esi} {:x} {:>2}",
                asc_id(&frame),
                len_to_dlc(frame.data.len()),
                frame.data.len()
            )?;
            write_hex_bytes(out, frame.data)?;
            writeln!(out, " 0 0 {fd_flags:X} 0 0 0 0 0")?;
        } else if frame.flags & flags::RTR != 0 {
            writeln!(out, "{channel}  {:<15} {direction:<4} r", asc_id(&frame))?;
        } else {
            write!(
                out,
                "{channel}  {:<15} {direction:<4} d {}",
                asc_id(&frame),
                frame.data.len()
            )?;
            write_hex_bytes(out, frame.data)?;
            writeln!(out)?;
        }
    }
    writeln!(out, "End TriggerBlock")
}

/// PEAK TRC 2.1 with a bus column, offsets in milliseconds from the UTC midnight before the
/// first frame so that `$STARTTIME` is a whole number of days.
pub fn write_trc(store: &FrameStore, out: &mut impl Write) -> io::Result<()> {
    const NS_PER_DAY: i64 = 86_400 * 1_000_000_000;
    let start_day = store.first_ts_ns().unwrap_or(0).div_euclid(NS_PER_DAY);
    writeln!(out, ";$FILEVERSION=2.1")?;
    writeln!(out, ";$STARTTIME={}", start_day + 25_569)?;
    writeln!(out, ";$COLUMNS=N,O,T,B,I,d,R,L,D")?;
    writeln!(out, ";")?;
    writeln!(out, ";   Generated by FreeCAN Studio sample-gen")?;
    writeln!(
        out,
        ";---+-- ------+------ +- +- --+----- +- +- +--- +- -- -- -- -- -- -- --"
    )?;
    for index in 0..store.len() {
        let frame = store.frame(index);
        let offset_ns = frame.ts_ns - start_day * NS_PER_DAY;
        let direction = if frame.flags & flags::TX != 0 {
            "Tx"
        } else {
            "Rx"
        };
        let kind =
            match frame.flags & (flags::FD | flags::BRS | flags::ESI | flags::RTR | flags::ERROR) {
                f if f & flags::ERROR != 0 => "ER",
                f if f & flags::RTR != 0 => "RR",
                f if f & flags::FD == 0 => "DT",
                f if f & (flags::BRS | flags::ESI) == flags::BRS | flags::ESI => "BI",
                f if f & flags::BRS != 0 => "FB",
                f if f & flags::ESI != 0 => "FE",
                _ => "FD",
            };
        let id = if frame.flags & flags::ERROR != 0 {
            "-".to_owned()
        } else if frame.id & EXT_FLAG != 0 {
            format!("{:08X}", frame.id & !EXT_FLAG)
        } else {
            format!("{:04X}", frame.id)
        };
        write!(
            out,
            "{:7} {:9}.{:03} {kind} {:>2} {id:>8} {direction} -  {:<4}",
            index + 1,
            offset_ns / 1_000_000,
            offset_ns % 1_000_000 / 1000,
            frame.channel + 1,
            len_to_dlc(frame.data.len())
        )?;
        write_hex_bytes(out, frame.data)?;
        writeln!(out)?;
    }
    Ok(())
}

/// CSV in python-can's column order plus channel and CAN FD flag columns, with seconds and
/// hex data, so that every frame of a log survives the trip.
pub fn write_csv(store: &FrameStore, out: &mut impl Write) -> io::Result<()> {
    writeln!(
        out,
        "timestamp,channel,arbitration_id,extended,remote,error,fd,brs,esi,dlc,data"
    )?;
    for index in 0..store.len() {
        let frame = store.frame(index);
        let bit = |flag: u8| u8::from(frame.flags & flag != 0);
        write!(
            out,
            "{}.{:06},{},0x{:x},{},{},{},{},{},{},{},",
            frame.ts_ns.div_euclid(1_000_000_000),
            frame.ts_ns.rem_euclid(1_000_000_000) / 1000,
            store.channels()[usize::from(frame.channel)],
            frame.id & !EXT_FLAG,
            u8::from(frame.id & EXT_FLAG != 0),
            bit(flags::RTR),
            bit(flags::ERROR),
            bit(flags::FD),
            bit(flags::BRS),
            bit(flags::ESI),
            frame.data.len()
        )?;
        for byte in frame.data {
            write!(out, "{byte:02x}")?;
        }
        writeln!(out)?;
    }
    Ok(())
}

/// Vector BLF: objects with version 1 headers and nanosecond timestamps from the second of
/// the first frame, packed into zlib log containers of about 128 KiB. Classic frames go in
/// CAN_MESSAGE objects, CAN FD frames in CAN_FD_MESSAGE_64 and error frames in
/// CAN_ERROR_EXT. The file header is rewritten at the end with the sizes and object count.
pub fn write_blf(store: &FrameStore, out: &mut (impl Write + Seek)) -> io::Result<()> {
    const CONTAINER_BYTES: usize = 128 << 10;
    let start_s = store.first_ts_ns().unwrap_or(0).div_euclid(1_000_000_000);
    let end_s = store.last_ts_ns().unwrap_or(0).div_euclid(1_000_000_000);
    let header_at = out.stream_position()?;
    out.write_all(&blf_file_header(start_s, end_s, 0, 0, 0))?;
    let mut objects = Vec::with_capacity(CONTAINER_BYTES + 256);
    let mut uncompressed_bytes = 0u64;
    for index in 0..store.len() {
        let frame = store.frame(index);
        let timestamp = (frame.ts_ns - start_s * 1_000_000_000) as u64;
        blf_frame_object(&mut objects, &frame, timestamp);
        if objects.len() >= CONTAINER_BYTES {
            uncompressed_bytes += objects.len() as u64;
            write_blf_container(out, &objects)?;
            objects.clear();
        }
    }
    if !objects.is_empty() {
        uncompressed_bytes += objects.len() as u64;
        write_blf_container(out, &objects)?;
    }
    let end_at = out.stream_position()?;
    out.seek(SeekFrom::Start(header_at))?;
    out.write_all(&blf_file_header(
        start_s,
        end_s,
        end_at - header_at,
        uncompressed_bytes,
        store.len() as u32,
    ))?;
    out.seek(SeekFrom::Start(end_at)).map(|_| ())
}

fn blf_file_header(
    start_s: i64,
    end_s: i64,
    file_bytes: u64,
    uncompressed_bytes: u64,
    object_count: u32,
) -> [u8; 144] {
    let mut header = [0u8; 144];
    header[..4].copy_from_slice(b"LOGG");
    header[4..8].copy_from_slice(&144u32.to_le_bytes());
    header[12] = 2;
    header[16..24].copy_from_slice(&file_bytes.to_le_bytes());
    header[24..32].copy_from_slice(&uncompressed_bytes.to_le_bytes());
    header[32..36].copy_from_slice(&object_count.to_le_bytes());
    header[40..56].copy_from_slice(&system_time(start_s));
    header[56..72].copy_from_slice(&system_time(end_s));
    header
}

/// A Windows SYSTEMTIME, in UTC, for a Unix time in seconds.
fn system_time(epoch_s: i64) -> [u8; 16] {
    let days = epoch_s.div_euclid(86_400);
    let seconds = epoch_s.rem_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    let fields = [
        year as u16,
        month as u16,
        (days + 4).rem_euclid(7) as u16,
        day as u16,
        (seconds / 3600) as u16,
        (seconds % 3600 / 60) as u16,
        (seconds % 60) as u16,
        0,
    ];
    let mut out = [0u8; 16];
    for (i, field) in fields.iter().enumerate() {
        out[i * 2..i * 2 + 2].copy_from_slice(&field.to_le_bytes());
    }
    out
}

fn blf_frame_object(out: &mut Vec<u8>, frame: &FrameRef<'_>, timestamp: u64) {
    const CAN_MESSAGE: u32 = 1;
    const CAN_ERROR_EXT: u32 = 73;
    const CAN_FD_MESSAGE_64: u32 = 101;
    const NANOSECONDS: u32 = 2;

    let channel = u16::from(frame.channel) + 1;
    let id = if frame.id & EXT_FLAG != 0 {
        (frame.id & !EXT_FLAG) | 0x8000_0000
    } else {
        frame.id
    };
    let transmitted = frame.flags & flags::TX != 0;
    let mut body = Vec::with_capacity(104);
    let kind = if frame.flags & flags::ERROR != 0 {
        body.extend_from_slice(&channel.to_le_bytes());
        body.extend_from_slice(&[0; 8]);
        body.push(frame.data.len() as u8);
        body.extend_from_slice(&[0; 13]);
        body.extend_from_slice(frame.data);
        body.resize(32, 0);
        CAN_ERROR_EXT
    } else if frame.flags & flags::FD != 0 {
        let mut fd_flags = 0x1000u32;
        if frame.flags & flags::BRS != 0 {
            fd_flags |= 0x2000;
        }
        if frame.flags & flags::ESI != 0 {
            fd_flags |= 0x4000;
        }
        body.push(frame.channel + 1);
        body.push(len_to_dlc(frame.data.len()));
        body.push(frame.data.len() as u8);
        body.push(0);
        body.extend_from_slice(&id.to_le_bytes());
        body.extend_from_slice(&0u32.to_le_bytes());
        body.extend_from_slice(&fd_flags.to_le_bytes());
        body.extend_from_slice(&[0; 18]);
        body.push(u8::from(transmitted));
        body.push(0);
        body.extend_from_slice(&0u32.to_le_bytes());
        body.extend_from_slice(frame.data);
        CAN_FD_MESSAGE_64
    } else {
        let mut message_flags = 0u8;
        if transmitted {
            message_flags |= 0x01;
        }
        if frame.flags & flags::RTR != 0 {
            message_flags |= 0x80;
        }
        body.extend_from_slice(&channel.to_le_bytes());
        body.push(message_flags);
        body.push(frame.data.len() as u8);
        body.extend_from_slice(&id.to_le_bytes());
        body.extend_from_slice(frame.data);
        body.resize(16, 0);
        CAN_MESSAGE
    };
    let object_size = (32 + body.len()) as u32;
    out.extend_from_slice(b"LOBJ");
    out.extend_from_slice(&32u16.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes());
    out.extend_from_slice(&object_size.to_le_bytes());
    out.extend_from_slice(&kind.to_le_bytes());
    out.extend_from_slice(&NANOSECONDS.to_le_bytes());
    out.extend_from_slice(&[0; 4]);
    out.extend_from_slice(&timestamp.to_le_bytes());
    out.extend_from_slice(&body);
    while !out.len().is_multiple_of(4) {
        out.push(0);
    }
}

fn write_blf_container(out: &mut impl Write, objects: &[u8]) -> io::Result<()> {
    const LOG_CONTAINER: u32 = 10;
    const ZLIB: u16 = 2;
    let compressed = miniz_oxide::deflate::compress_to_vec_zlib(objects, 6);
    let object_size = (32 + compressed.len()) as u32;
    out.write_all(b"LOBJ")?;
    out.write_all(&16u16.to_le_bytes())?;
    out.write_all(&1u16.to_le_bytes())?;
    out.write_all(&object_size.to_le_bytes())?;
    out.write_all(&LOG_CONTAINER.to_le_bytes())?;
    out.write_all(&ZLIB.to_le_bytes())?;
    out.write_all(&[0; 6])?;
    out.write_all(&(objects.len() as u32).to_le_bytes())?;
    out.write_all(&[0; 4])?;
    out.write_all(&compressed)?;
    let padding = (4 - object_size as usize % 4) % 4;
    out.write_all(&[0; 3][..padding])
}

/// ASAM MF4 bus logging: one sorted data group each for data, remote and error frames,
/// whose records hold a float64 time in seconds from the first frame's second and the
/// `CAN_DataFrame` members with a fixed 64-byte `DataBytes`. The records are written as
/// transposed, deflated DZ blocks in a DL list.
pub fn write_mf4(store: &FrameStore, out: &mut impl Write) -> io::Result<()> {
    let start_s = store.first_ts_ns().unwrap_or(0).div_euclid(1_000_000_000);
    let mut file = Mf4Writer::default();
    file.bytes.extend_from_slice(b"MDF     4.10    sample-g");
    file.bytes.resize(28, 0);
    file.bytes.extend_from_slice(&410u16.to_le_bytes());
    file.bytes.resize(64, 0);
    let mut header = Vec::new();
    header.extend_from_slice(&((start_s * 1_000_000_000) as u64).to_le_bytes());
    header.resize(32, 0);
    let header_at = file.block(b"##HD", &[0; 6], &header);

    let kinds = [
        ("CAN_DataFrame", flags::RTR | flags::ERROR, 0),
        ("CAN_RemoteFrame", flags::RTR, flags::RTR),
        ("CAN_ErrorFrame", flags::ERROR, flags::ERROR),
    ];
    let mut next_group = 0;
    for (name, mask, wanted) in kinds.into_iter().rev() {
        let mut records = Vec::new();
        for index in 0..store.len() {
            let frame = store.frame(index);
            if frame.flags & mask == wanted {
                mf4_record(&mut records, &frame, start_s);
            }
        }
        if records.is_empty() {
            continue;
        }
        let data = file.records(&records);
        let channels = file.can_frame_channels(name);
        let mut group = Vec::new();
        group.extend_from_slice(&0u64.to_le_bytes());
        group.extend_from_slice(&((records.len() / MF4_RECORD) as u64).to_le_bytes());
        group.extend_from_slice(&[0; 8]);
        group.extend_from_slice(&(MF4_RECORD as u32).to_le_bytes());
        group.extend_from_slice(&0u32.to_le_bytes());
        let channel_group = file.block(b"##CG", &[0, channels, 0, 0, 0, 0], &group);
        next_group = file.block(b"##DG", &[next_group, channel_group, data, 0], &[0; 8]);
    }
    file.set_link(header_at, 0, next_group);
    out.write_all(&file.bytes)
}

const MF4_RECORD: usize = 83;

/// t f64, BusChannel u8, ID u32 (bit 31 for 29-bit IDs), DLC u8, DataLength u8, DataBytes
/// [u8; 64], Dir u8, EDL u8, BRS u8, ESI u8.
fn mf4_record(out: &mut Vec<u8>, frame: &FrameRef<'_>, start_s: i64) {
    let seconds = (frame.ts_ns - start_s * 1_000_000_000) as f64 / 1e9;
    let id = if frame.flags & flags::ERROR != 0 {
        0
    } else if frame.id & EXT_FLAG != 0 {
        (frame.id & !EXT_FLAG) | 0x8000_0000
    } else {
        frame.id
    };
    let bit = |flag: u8| u8::from(frame.flags & flag != 0);
    out.extend_from_slice(&seconds.to_le_bytes());
    out.push(frame.channel + 1);
    out.extend_from_slice(&id.to_le_bytes());
    out.push(len_to_dlc(frame.data.len()));
    out.push(frame.data.len() as u8);
    let mut data = [0u8; 64];
    data[..frame.data.len()].copy_from_slice(frame.data);
    out.extend_from_slice(&data);
    out.extend_from_slice(&[
        bit(flags::TX),
        bit(flags::FD),
        bit(flags::BRS),
        bit(flags::ESI),
    ]);
}

#[derive(Default)]
struct Mf4Writer {
    bytes: Vec<u8>,
}

impl Mf4Writer {
    fn block(&mut self, id: &[u8; 4], links: &[u64], data: &[u8]) -> u64 {
        while !self.bytes.len().is_multiple_of(8) {
            self.bytes.push(0);
        }
        let at = self.bytes.len() as u64;
        let length = 24 + links.len() * 8 + data.len();
        self.bytes.extend_from_slice(id);
        self.bytes.extend_from_slice(&[0; 4]);
        self.bytes.extend_from_slice(&(length as u64).to_le_bytes());
        self.bytes
            .extend_from_slice(&(links.len() as u64).to_le_bytes());
        for link in links {
            self.bytes.extend_from_slice(&link.to_le_bytes());
        }
        self.bytes.extend_from_slice(data);
        at
    }

    fn set_link(&mut self, block_at: u64, index: usize, target: u64) {
        let at = block_at as usize + 24 + index * 8;
        self.bytes[at..at + 8].copy_from_slice(&target.to_le_bytes());
    }

    fn text(&mut self, text: &str) -> u64 {
        let mut data = text.as_bytes().to_vec();
        data.push(0);
        self.block(b"##TX", &[], &data)
    }

    /// A CN block. `kind` is (channel type, sync type, data type), `place` is (byte
    /// offset, bit count) and `links` is (next channel, composition).
    fn channel(
        &mut self,
        name: &str,
        kind: (u8, u8, u8),
        place: (u32, u32),
        links: (u64, u64),
    ) -> u64 {
        let (cn_type, sync_type, data_type) = kind;
        let (byte_offset, bit_count) = place;
        let (next, composition) = links;
        let name = self.text(name);
        let mut data = vec![cn_type, sync_type, data_type, 0];
        data.extend_from_slice(&byte_offset.to_le_bytes());
        data.extend_from_slice(&bit_count.to_le_bytes());
        data.resize(72, 0);
        self.block(b"##CN", &[next, composition, name, 0, 0, 0, 0, 0], &data)
    }

    /// The time master channel, then a structure channel named `structure` whose members
    /// describe the rest of the record.
    fn can_frame_channels(&mut self, structure: &str) -> u64 {
        const UNSIGNED: u8 = 0;
        const FLOAT: u8 = 4;
        const BYTES: u8 = 10;
        let members: [(&str, u8, u32, u32); 9] = [
            ("BusChannel", UNSIGNED, 8, 8),
            ("ID", UNSIGNED, 9, 32),
            ("DLC", UNSIGNED, 13, 8),
            ("DataLength", UNSIGNED, 14, 8),
            ("DataBytes", BYTES, 15, 512),
            ("Dir", UNSIGNED, 79, 8),
            ("EDL", UNSIGNED, 80, 8),
            ("BRS", UNSIGNED, 81, 8),
            ("ESI", UNSIGNED, 82, 8),
        ];
        let mut next = 0;
        for (member, data_type, byte_offset, bit_count) in members.into_iter().rev() {
            let name = format!("{structure}.{member}");
            next = self.channel(
                &name,
                (0, 0, data_type),
                (byte_offset, bit_count),
                (next, 0),
            );
        }
        let structure = self.channel(structure, (0, 0, BYTES), (8, 600), (0, next));
        self.channel("t", (2, 1, FLOAT), (0, 64), (structure, 0))
    }

    fn records(&mut self, records: &[u8]) -> u64 {
        const BLOCK_RECORDS: usize = 12_000;
        let mut blocks = Vec::new();
        for part in records.chunks(BLOCK_RECORDS * MF4_RECORD) {
            let transposed = transpose(part, MF4_RECORD);
            let compressed = miniz_oxide::deflate::compress_to_vec_zlib(&transposed, 6);
            let mut data = b"DT".to_vec();
            data.push(1);
            data.push(0);
            data.extend_from_slice(&(MF4_RECORD as u32).to_le_bytes());
            data.extend_from_slice(&(part.len() as u64).to_le_bytes());
            data.extend_from_slice(&(compressed.len() as u64).to_le_bytes());
            data.extend_from_slice(&compressed);
            blocks.push(self.block(b"##DZ", &[], &data));
        }
        let mut links = vec![0u64];
        links.extend_from_slice(&blocks);
        let mut data = vec![0u8; 4];
        data.extend_from_slice(&(blocks.len() as u32).to_le_bytes());
        for index in 0..blocks.len() {
            let offset = (index * BLOCK_RECORDS * MF4_RECORD) as u64;
            data.extend_from_slice(&offset.to_le_bytes());
        }
        self.block(b"##DL", &links, &data)
    }
}

/// The bytes of `columns`-byte rows regrouped column by column, as a transposing DZ block
/// stores them.
fn transpose(data: &[u8], columns: usize) -> Vec<u8> {
    let rows = data.len() / columns;
    let mut out = data.to_vec();
    for row in 0..rows {
        for column in 0..columns {
            out[column * rows + row] = data[row * columns + column];
        }
    }
    out
}

fn asc_id(frame: &FrameRef<'_>) -> String {
    if frame.id & EXT_FLAG != 0 {
        format!("{:X}x", frame.id & !EXT_FLAG)
    } else {
        format!("{:X}", frame.id)
    }
}

fn write_hex_bytes(out: &mut impl Write, data: &[u8]) -> io::Result<()> {
    for byte in data {
        write!(out, " {byte:02X}")?;
    }
    Ok(())
}

/// The CAN FD DLC code for a payload length, rounding up to the next code.
fn len_to_dlc(len: usize) -> u8 {
    const LENGTHS: [usize; 7] = [12, 16, 20, 24, 32, 48, 64];
    if len <= 8 {
        return len as u8;
    }
    LENGTHS
        .iter()
        .position(|&l| len <= l)
        .map_or(15, |i| 9 + i as u8)
}

/// `Tue Sep 30 00:00:00.000 2025` for a Unix time in seconds, in UTC.
fn asc_date(epoch_s: i64) -> String {
    const DAYS: [&str; 7] = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    const MONTHS: [&str; 12] = [
        "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ];
    let days = epoch_s.div_euclid(86_400);
    let seconds = epoch_s.rem_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    format!(
        "{} {} {day} {:02}:{:02}:{:02}.000 {year}",
        DAYS[(days + 4).rem_euclid(7) as usize],
        MONTHS[month as usize - 1],
        seconds / 3600,
        seconds % 3600 / 60,
        seconds % 60
    )
}

/// The proleptic Gregorian date `days` after 1970-01-01.
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let day_of_era = z.rem_euclid(146_097);
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_from_march = (5 * day_of_year + 2) / 153;
    let day = (day_of_year - (153 * month_from_march + 2) / 5 + 1) as u32;
    let month = if month_from_march < 10 {
        month_from_march + 3
    } else {
        month_from_march - 9
    } as u32;
    let year = year_of_era + era * 400 + i64::from(month <= 2);
    (year, month, day)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dates_and_dlcs() {
        assert_eq!(asc_date(0), "Thu Jan 1 00:00:00.000 1970");
        assert_eq!(asc_date(1_759_190_400), "Tue Sep 30 00:00:00.000 2025");
        assert_eq!(asc_date(951_782_400 + 3661), "Tue Feb 29 01:01:01.000 2000");
        assert_eq!(len_to_dlc(8), 8);
        assert_eq!(len_to_dlc(9), 9);
        assert_eq!(len_to_dlc(12), 9);
        assert_eq!(len_to_dlc(33), 14);
        assert_eq!(len_to_dlc(64), 15);
    }
}
